# <u>Training Exercices - Matrices<u>

__<u>Jorge Pineño Pérez<u>__ / Module 0 - Building Blocks

__<u>Training Exercise M.1<u>__

__1.__

Model: $ y = Xb + e $

In [3]:
# import numpy to use arrays as matrices
import numpy as np

# create the matrices and variables of the exercise
y = np.array([[15.1],
            [7.9],
            [4.5],
            [12.8],
            [10.5]])

X = np.array([[1, 25.5, 1.23],
            [1, 40.8, 1.89],
            [1, 30.2, 1.55],
            [1, 4.3, 1.18],
            [1, 10.7, 1.68]])

b1 = np.array([[23],
              [0.1],
              [-8]])

b2 = np.array([[22],
              [-0.2],
              [-7]])

__2.__

To know which of the two candidates for $b$ reduces $e$, we need to resolve the following equation, first using the vector `b1`, and then using `b2`:

$$e = y - XB$$

In [5]:
e1 = y - X@b1
e1

array([[-0.61],
       [-4.06],
       [-9.12],
       [-1.19],
       [-0.13]])

In [6]:
e2 = y - X@b2
e2

array([[ 6.81],
       [ 7.29],
       [-0.61],
       [-0.08],
       [ 2.4 ]])

We can now measure the distance from 0 of every element inside `e1` and `e2`, and then compare the results

In [8]:
sum(abs(e1[i]) for i in range(5))

array([15.11])

In [9]:
sum(abs(e2[i]) for i in range(5))

array([17.19])

As we can see, the unexplained part of the model is minimised by using `b1`, as $\sum_{i=1}^{5} |e1_i| < \sum_{i=1}^{5} |e2_i|$

__3.__

We identify $A$ as a matrix of dimensions $p \times q$

We identify $u$ as a row vector of dimensions $1 \times p$

We identify $v$ as a vector of dimensions $q \times 1$

We need to compute the dimensions of $d = u · A · v$

Firstly, the dimensions of the row vector $uA$ resulting from $u · A$ will be $1 \times q$

Secondly, the dimensions of the result of the row vector $uA$ with dimensions $1 \times q$ multiplied by $v$ will be $1 \times 1$

Finally, we can express our steps in sigma notation:

$$u · A = [\sum_{k=1}^pu_k · A_{k,1}, \sum_{k=1}^pu_k · A_{k,2}, ..., \sum_{k=1}^pu_k · A_{k,q}]$$
$$u · A = \sum_{k=1}^pu_k · A_{k,i}$$
$$d = \sum_{i=1}^q(u · A)_i · v_i$$
$$d = \sum_{i=1}^q\sum_{k=1}^pu_k · A_{k,i} · v_i$$

__4.__

We identify $A$ as a matrix of dimensions $p \times p$

We identify $I$ as the identity matrix of dimensions $p \times p$

To answer the question, $(A + I)^2 = (A + I)(A + I)$

This can be expanded as $(A + I)^2 = A^2 + AI + IA + I^2$, and finally, as $(A + I)^2 = A^2 + 2A + I$

This is so, because multiplying any matrix by the identity matrix, or vice versa, results in the original matrix (the one which is not the identity), and the identity matrix multiplied by itself is still the identity matrix

__<u>Training Exercise M.2<u>__

__1.__

Expression to simplify: $ (a + b)'(a + b) $, given that $a$ and $b$ are two $(p \times 1)$ vectors:

$$ (a + b)'(a + b) = $$
$$ = (a' + b')(a + b) = $$
$$ = a'a + a'b + b'a + b'b = $$
$$ because \space b'a = a'b, \space and \space they \space are \space scalars, \space = a'a + 2a'b + b'b $$

__2.__

For $a$, a $(p \times 1)$ vector, we can show that $a'a = tr(aa')$ the following way:

$$if \space a = \begin{pmatrix}
a_{11}\\
a_{21}\\
...\\
a_{p1}
\end{pmatrix} \space;\space then \space a' = \begin{pmatrix}
a_{11} & a_{21} & ... & a_{p1}
\end{pmatrix}$$

$$a'a = a_{11}^2 + a_{21}^2 + ... + a_{p1}^2 \space ;$$
$$aa' = \begin{pmatrix}
a_{11}^2 & a_{11}a_{21} & ... & a_{11}a_{1p} \\
a_{21}a_{11} & a_{21}^2 & ... & a_{21}a_{1p} \\
... & ... & ... & ... \\
a_{p1}a_{11} & a_{p1}a_{21} & ... & a_{p1}^2
\end{pmatrix} \space ;$$
$$tr(aa') = a_{11}^2 + a_{21}^2 + ... + a_{p1}^2 = \sum_{i=1}^p a_{i}^2 = a'a$$

__3.__

For $A$, a $(p \times p)$ (square) matrix, and $c$, a scalar, we can show that $tr(cA) = c·tr(A)$ the following way:

$$if \space A = \begin{pmatrix}
a_{11} & a_{12} & ... & a_{1p}\\
a_{21} & a_{22} & ... & a_{2p}\\
... & ... & ... & ...\\
a_{p1} & a_{p2} & ... & a_{pp}
\end{pmatrix} \space ; \space then \space cA = \begin{pmatrix}
ca_{11} & ca_{12} & ... & ca_{1p}\\
ca_{21} & ca_{22} & ... & ca_{2p}\\
... & ... & ... & ...\\
ca_{p1} & ca_{p2} & ... & ca_{pp}
\end{pmatrix}$$
$$then, \space tr(A) = a_{11} · a_{22} · \space ... \space · a_{pp}$$
$$finally, \space tr(cA) = ca_{11} · ca_{22} · \space ... \space · ca_{pp} = c · (a_{11} · a_{22} · \space ... \space · a_{pp}) \space ;$$
$$so, \space tr(cA) = c \sum_{i=1}^p a_{ii} = c·tr(A)$$

__4.__

For $A$, a $(p \times p)$ (square) matrix, and $c \neq 0$, a scalar, we can find $B = (cA)^{-1}$ the following way:

$$B = (cA)^{-1} = c^{-1} \space · \space A^{-1} \space ;$$
$$so, \space B = 1 / c \space · \space A^{-1} = A^{-1} / c \space ;$$
$$i.e. \space B = \begin{pmatrix}
{a/c}_{11} & {a/c}_{12} & ... & {a/c}_{1p}\\
{a/c}_{21} & {a/c}_{22} & ... & {a/c}_{2p}\\
... & ... & ... & ...\\
{a/c}_{p1} & {a/c}_{p2} & ... & {a/c}_{pp}
\end{pmatrix}$$

__5.__

For $A$, a $(2 \times 2)$ matrix, and $B(f)$, we can find $A^{-1}$ the following way:

1. We recognise that, for $B$ to give $A^{-1}$, it would have to check the following relation:
$$B \space · \space A = A \space · \space B = I \space ;$$
$$then, \space B \space · \space A = A \space · \space B = I \space = \begin{pmatrix}
a & b\\
c & d
\end{pmatrix} \space · \space \begin{pmatrix}
d & -b\\
-c & a
\end{pmatrix} = \begin{pmatrix}
1 & 0\\
0 & 1
\end{pmatrix} \space ;$$
$$so, \space \begin{pmatrix}
ad-bc & -ab+ba\\
cd-cd & -bc+ad
\end{pmatrix} = \begin{pmatrix}
1 & 0\\
0 & 1
\end{pmatrix}$$

2. From here, we can see that $ad-bc = 0, \space and \space cd-cd = 0$, and, of course, $ad-bc = -bc+ad$
3. Therefore, $f = ad-bc \space , \space s.t. \space ad-bc / f = 1$

Finally, the inverse will only exist if $ad \neq bc$

__6.__

First, $ι'ι = \sum_{i=1}^p ι_{i}^2$, and because $ι$ is the unit vector, $ι'ι = \sum_{i=1}^p 1 = p$

Second, $(ιι')^2 = ι \space · \space ι \space · \space (ι'ι) \space · \space ι' = pιι'$

__<u>Training Exercise M.3<u>__

__1.__

If $b$ is a $(p \times 1)$ vector, and $f(b) = b'b$, the gradient vector and Hessian matrix are:

$$f(b) = b'b = \sum_{i=1}^pb_i^2\space;
\space\frac{\partial f}{\partial b_i}(b) = 2b_i\space;
\space\frac{\partial f}{\partial b}(b) = 2b$$
$$\frac{\partial^2 f}{\partial b_i \partial b'_i}(b) = 2I_p$$

__2.__

If $A$ is a $(q \times q)$ diagonal matrix, and $x$ is a $(q \times 1)$ vector, we can prove that $A$ will be  positive definite if all diagonal elements are positive, and negative definite if all diagonal elements are negative

$$A = \begin{pmatrix}
a_{11} & 0 & ... & 0 \\
0 & a_{22} & ... & 0 \\
... & ... & ... & ... \\
0 & 0 & ... & a_{qq}
\end{pmatrix}\space;
\space x = \begin{pmatrix}
x_{11} \\
x_{21} \\
... \\
x_{q1}
\end{pmatrix}$$

We first calculate $x'Ax$:

$$x'A = \begin{pmatrix}
x_{11}a_{11} & x_{21}a_{22} & ... & x_{q1}a_{qq}
\end{pmatrix}$$
$$x'Ax = x_{11}a_{11}x_{11} + x_{21}a_{22}x_{21} + \dots + x_{q1}a_{qq}x_{q1} = x_{11}^2a_{11} + x_{21}^2a_{22} + \dots + x_{q1}^2a_{qq} = \sum_{\substack{i=1 \\ j=1}}^q x_{j1}^2a_{ji}$$

From our result, we can see that if $x \neq 0$, and $a_{ji} > 0$, the diagonal matrix will be positive definite. Alternatively, if $a_{ji} < 0$, the diagonal matrix will be negative definite